version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    labels:
      - dependencies
      - npm
    groups:
      npm:
        patterns:
          - "*"
