blank_issues_enabled: false

contact_links:
  - name: Questions / Usage help
    url: https://github.com/sighanse/otterscript-vscode/discussions
    about: Ask questions or discuss usage here.

  - name: Bug reports
    url: https://github.com/sighanse/otterscript-vscode/issues/new/choose
    about: Report bugs or issues here.

  - name: Security issues
    url: https://github.com/sighanse/otterscript-vscode/security
    about: Report security vulnerabilities privately

  - name: Extension Documentation
    url: https://github.com/sighanse/otterscript-vscode#readme
    about: Read the extension documentation and settings guide
